language: java

branches:
  only:
    - master

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn clean install; fi'

deploy:
  provider: heroku
  app: heig-pro-b04
  api_key: $HEROKU_TOKEN
  on:
    branch: master
    repo: heig-PRO-b04/java-backend
