name: Documentation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Update Wiki
        run : |
          cd wiki/
          git init .
          git add .
          git commit -m "Wiki update"
          git remote add origin https://${{GH_PERSONAL_ACCESS_TOKEN}}@github.com/${{GITHUB_REPOSITORY}}.wiki.git
          git push -u origin master --force
